package main

// `batten pr` — the pull request that writes itself, from the record rather than from a summary.
//
// The gate does not change: it still denies, still demands two verdicts from two producers,
// still requires cited evidence. What changes is what you GET for passing.
//
// The finding that makes this worth building: GitHub has rendered Mermaid natively in pull
// request descriptions, issues, comments and wikis since February 2022. No plugin, no hosted
// images, none of the sanitising that inline SVG gets. And batten has had the run's DAG sitting
// in SQLite with typed edges — spawn, depends_on, retry_of, supersedes, rollback — since the
// beginning. Emitting it as Mermaid is rendering, not new machinery.
//
// It is also the only surface here that distributes itself: a PR is read by reviewers, and every
// one of them sees the footer.
//
// THE NON-NEGOTIABLE: if usage was not measured, the table says NOT MEASURED — never $0.00. If
// the reviewer's verdict is missing, the table says so. A generated PR that flatters the run is
// worse than no generated PR, because it is the one artefact other people will read without
// knowing what to distrust.

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ArthurZizumbo/batten/internal/render"
	"github.com/ArthurZizumbo/batten/internal/spec"
	"github.com/ArthurZizumbo/batten/internal/store"
)

func cmdPR(args []string) error {
	if len(args) < 1 || strings.HasPrefix(args[0], "--") {
		return errors.New("pr: batten pr <unit> [--out <path>]")
	}
	unit, out := args[0], ""
	for i := 1; i < len(args); i++ {
		switch args[i] {
		case "--out":
			if i+1 >= len(args) {
				return errors.New("pr: --out needs a path")
			}
			out, i = args[i+1], i+1
		default:
			return fmt.Errorf("pr: unknown flag %q", args[i])
		}
	}

	sp, st, err := load()
	if err != nil {
		return err
	}
	defer st.Close()

	run, err := st.LatestRun(sp.Project, unit)
	if err != nil {
		return fmt.Errorf("no run recorded for %s", unit)
	}
	body, err := renderPR(sp, st, run)
	if err != nil {
		return err
	}

	if out == "" {
		fmt.Print(body)
		return nil
	}
	if err := os.WriteFile(out, []byte(body), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", out)
	fmt.Printf("open the PR with: gh pr create --body-file %s\n", out)
	return nil
}

// renderPR builds the whole body. Every number in it is read from the run record; nothing is
// summarised by a model and nothing is estimated.
func renderPR(sp *spec.Spec, st *store.Store, run *store.Run) (string, error) {
	nodes, err := st.Nodes(run.RunID)
	if err != nil {
		return "", err
	}
	edges, err := st.Edges(run.RunID)
	if err != nil {
		return "", err
	}
	ws, _ := st.WriteSetsByRun(run.RunID)
	usg, _ := st.UsageByNode(run.RunID)
	reviewer, rErr := st.LatestVerdictNotBySource(run.RunID, "", "batten")
	batten, bErr := st.LatestVerdictBySource(run.RunID, "", "batten")

	// Counted here rather than inside the header, which does not see the edges. A retry count
	// that could never fire would be one more capability declared and not delivered.
	retries := 0
	for _, e := range edges {
		if e.Rel == "retry_of" {
			retries++
		}
	}

	var b strings.Builder
	writePRHeader(&b, sp, run, nodes, retries, reviewer, batten, rErr == nil, bErr == nil)
	writeMermaid(&b, nodes, edges, ws, reviewer, batten, rErr == nil, bErr == nil)
	writeVerification(&b, reviewer, batten, rErr == nil, bErr == nil)
	writeCost(&b, run, nodes, usg, ws)
	b.WriteString("\n<sub>Generated by [batten](https://github.com/ArthurZizumbo/batten). " +
		"The graph and the evidence come from the run record, not from a model's summary.</sub>\n")
	return b.String(), nil
}

func writePRHeader(b *strings.Builder, sp *spec.Spec, run *store.Run, nodes []store.Node,
	retries int, reviewer, batten *store.Verdict, hasReviewer, hasBatten bool) {

	title := run.UnitID
	if t := unitTitle(sp, run.UnitID); t != "" {
		title += " — " + t
	}
	fmt.Fprintf(b, "## %s\n\n", title)

	// The badge is the first thing anyone reads, so it must be the honest one. "batten-verified"
	// is reserved for a gate that is actually satisfied: both verdicts present, both ok, and the
	// reviewer's citing something.
	subs := 0
	for _, n := range nodes {
		if n.Kind == "subagent" {
			subs++
		}
	}
	verified := hasBatten && batten.Result == "ok" &&
		hasReviewer && reviewer.Result == "ok" && len(reviewer.Evidence) > 0
	if verified {
		fmt.Fprintf(b, "**batten-verified** · 2 verdicts · %d subagent(s)", subs)
	} else {
		fmt.Fprintf(b, "**⚠ NOT batten-verified** — %s · %d subagent(s)",
			shortfall(reviewer, batten, hasReviewer, hasBatten), subs)
	}
	if retries > 0 {
		fmt.Fprintf(b, " · %d retry/retries", retries)
	}
	b.WriteString("\n\n")
}

// shortfall names what the gate is still missing, in a phrase that fits a badge line.
func shortfall(reviewer, batten *store.Verdict, hasReviewer, hasBatten bool) string {
	switch {
	case !hasReviewer && !hasBatten:
		return "no verdict at all"
	case !hasBatten:
		return "the declared checks were never run"
	case batten.Result != "ok":
		return "the declared checks did not pass"
	case !hasReviewer:
		return "nobody judged the work against its criteria"
	case len(reviewer.Evidence) == 0:
		return "the reviewer's approval cites nothing"
	case reviewer.Result != "ok":
		return "the reviewer said " + reviewer.Result
	}
	return "the gate is not satisfied"
}

// writeMermaid draws the path the run ACTUALLY took. A plan diagram cannot show a retry; this
// can, because the edges are typed and the retry_of edge is in the database.
func writeMermaid(b *strings.Builder, nodes []store.Node, edges []store.Edge,
	ws map[string][]string, reviewer, batten *store.Verdict, hasReviewer, hasBatten bool) {

	b.WriteString("```mermaid\ngraph LR\n")

	ids := map[string]string{} // node id -> mermaid id
	i := 0
	safe := func(nodeID string) string {
		if id, ok := ids[nodeID]; ok {
			return id
		}
		i++
		id := fmt.Sprintf("N%d", i)
		ids[nodeID] = id
		return id
	}

	sort.Slice(nodes, func(a, c int) bool { return nodes[a].StartedAt < nodes[c].StartedAt })

	for _, n := range nodes {
		id := safe(n.NodeID)
		label := mermaidLabel(n, ws[n.NodeID])
		// Quoted labels, always. Mermaid does not reliably parse `<br/>` or punctuation in a
		// bare label, and a broken block renders on GitHub as a raw error box in the middle of
		// the pull request — which is worse than no diagram, because it looks like batten broke.
		switch n.Kind {
		case "phase":
			fmt.Fprintf(b, "  %s[\"%s\"]:::%s\n", id, label, mermaidClass(n.Status))
		default:
			fmt.Fprintf(b, "  %s(\"%s\"):::%s\n", id, label, mermaidClass(n.Status))
		}
	}

	for _, e := range edges {
		src, okS := ids[e.Src]
		dst, okD := ids[e.Dst]
		if !okS || !okD {
			continue // an edge to a node this run does not have: drawing it would invent a box
		}
		switch e.Rel {
		case "spawn":
			fmt.Fprintf(b, "  %s --> %s\n", src, dst)
		case "retry_of":
			// Dotted and labelled: the retry is the whole reason this graph is worth drawing.
			fmt.Fprintf(b, "  %s -.retry_of.-> %s\n", src, dst)
		default:
			fmt.Fprintf(b, "  %s -- %s --> %s\n", src, e.Rel, dst)
		}
	}

	// The gate, as its own terminal node, because it is what the reader came to find out.
	gateLabel, gateClass := "gate: no verdict", "fail"
	switch {
	case hasBatten && hasReviewer && batten.Result == "ok" && reviewer.Result == "ok":
		gateLabel, gateClass = "gate: PASSED", "ok"
	case hasBatten && batten.Result != "ok":
		gateLabel, gateClass = "gate: checks failed", "fail"
	case hasReviewer && !hasBatten:
		gateLabel, gateClass = "gate: checks not run", "warn"
	case hasBatten && !hasReviewer:
		gateLabel, gateClass = "gate: not reviewed", "warn"
	}
	fmt.Fprintf(b, "  G{{\"%s\"}}:::%s\n", gateLabel, gateClass)
	// Hang the gate off the last PHASE. Hanging it off whichever node happened to sort last drew
	// the gate as the consequence of one arbitrary subagent, which is not what a gate is.
	tail := ""
	for _, n := range nodes {
		if n.Kind == "phase" {
			tail = n.NodeID
		}
	}
	if tail == "" && len(nodes) > 0 {
		tail = nodes[len(nodes)-1].NodeID
	}
	if tail != "" {
		fmt.Fprintf(b, "  %s --> G\n", safe(tail))
	}

	// GitHub's own status colours, so the diagram matches the rest of the page.
	b.WriteString("  classDef ok fill:#1a7f37,color:#fff,stroke:#1a7f37\n")
	b.WriteString("  classDef fail fill:#cf222e,color:#fff,stroke:#cf222e\n")
	b.WriteString("  classDef warn fill:#9a6700,color:#fff,stroke:#9a6700\n")
	b.WriteString("  classDef running fill:#0969da,color:#fff,stroke:#0969da\n")
	b.WriteString("```\n\n")
}

// mermaidLabel keeps the label readable and, crucially, escaped. A domain or agent name with a
// bracket or a quote in it would otherwise break the diagram — and a broken Mermaid block on
// GitHub renders as a raw error box in the middle of the PR.
func mermaidLabel(n store.Node, files []string) string {
	// Domain first, then the agent id. The agent TYPE last: four subagents all labelled
	// "domain-agent" tell a reviewer nothing about which box is which.
	label := n.Domain
	if label == "" {
		label = n.AgentID
	}
	if label == "" {
		label = n.Label
	}
	if label == "" {
		label = "node"
	}
	label = mermaidEscape(label)
	// The attempt number, on retries only. Without it a reviewer looking at a red `backend` and a
	// green `backend` sees two boxes and no way to tell which one is the second try — the dotted
	// edge says a retry happened, this says which box IS the retry.
	if n.Attempt > 1 {
		label += fmt.Sprintf(" #%d", n.Attempt)
	}

	switch n.Status {
	case "ok":
		label += " ✓"
	case "failed", "blocked":
		label += " ✗"
	}
	if n.Kind == "subagent" {
		switch len(files) {
		case 0:
			// Not "0 files": nobody recorded a write-set, which is a different fact.
			label += "<br/>write-set not recorded"
		case 1:
			label += "<br/>1 file"
		default:
			label += fmt.Sprintf("<br/>%d files", len(files))
		}
	}
	return label
}

// mermaidEscape neutralises the characters that terminate a node label. Mermaid has no escape
// syntax worth relying on, so the characters are replaced rather than escaped.
func mermaidEscape(s string) string {
	r := strings.NewReplacer(
		`"`, "'", "[", "(", "]", ")", "{", "(", "}", ")",
		"|", "/", "<", "‹", ">", "›", "\n", " ", "\r", " ",
	)
	return r.Replace(s)
}

func mermaidClass(status string) string {
	switch status {
	case "ok":
		return "ok"
	case "failed", "blocked":
		return "fail"
	case "running":
		return "running"
	}
	return "warn"
}

func writeVerification(b *strings.Builder, reviewer, batten *store.Verdict, hasReviewer, hasBatten bool) {
	b.WriteString("### Verification\n\n")
	b.WriteString("| producer | result | evidence |\n|---|---|---|\n")

	row := func(who string, v *store.Verdict, present bool, missing string) {
		if !present {
			fmt.Fprintf(b, "| %s | ⚠ **missing** | %s |\n", who, missing)
			return
		}
		mark := "✅"
		if v.Result != "ok" {
			mark = "❌"
		}
		ev := "**none cited** — an approval that points at nothing is not an approval"
		if len(v.Evidence) > 0 {
			var parts []string
			for _, e := range v.Evidence {
				parts = append(parts, "`"+tableCell(firstLineOf(e))+"`")
			}
			ev = strings.Join(parts, " · ")
		}
		fmt.Fprintf(b, "| %s | %s %s | %s |\n", who, mark, v.Result, ev)
	}

	row("batten (mechanical)", batten, hasBatten,
		"the gate's declared checks were never run — `batten check`")
	row("reviewer (criteria)", reviewer, hasReviewer,
		"nobody judged this work against its acceptance criteria")
	b.WriteString("\n")
}

// tableCell keeps a value from breaking out of a markdown table row.
func tableCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "`", "'")
	if len(s) > 120 {
		s = s[:117] + "..."
	}
	return s
}

func writeCost(b *strings.Builder, run *store.Run, nodes []store.Node,
	usg map[string]store.Usage, ws map[string][]string) {

	b.WriteString("### What it cost\n\n|  |  |\n|---|---|\n")

	subs := 0
	for _, n := range nodes {
		if n.Kind == "subagent" {
			subs++
		}
	}
	// The line the whole principle hangs on. A run nobody ingested a transcript for has NOT
	// spent zero, and this table is exactly where a zero would be believed.
	if run.TokensSpent > 0 {
		fmt.Fprintf(b, "| tokens | %s across %d subagent(s) |\n", render.Tokens(run.TokensSpent), subs)
		switch {
		case run.ImputedUSD > 0 && run.UnpricedTokens > 0:
			// Partially priced: the dollars for the unpriced share do not exist, so the
			// figure is a floor — and the PR is the one artifact strangers read without
			// knowing what to distrust, so it says so in place.
			fmt.Fprintf(b, "| imputed | **≥$%.2f — a floor, not a total**: %d%% of the tokens have no "+
				"published rate *(never a bill: what the priced share would have cost on the API)* |\n",
				run.ImputedUSD, render.UnpricedShare(run.UnpricedTokens, run.TokensSpent))
		case run.ImputedUSD > 0:
			fmt.Fprintf(b, "| imputed | $%.2f *(not a bill: what these tokens would have cost on "+
				"the API, and on a subscription the marginal cost of a token is zero)* |\n", run.ImputedUSD)
		default:
			b.WriteString("| imputed | **not priced** — no published API rate for this run's model |\n")
		}
	} else {
		b.WriteString("| tokens | **NOT MEASURED** — no transcript was ingested for this run. " +
			"Not zero: unknown |\n")
		b.WriteString("| imputed | **NOT MEASURED** |\n")
	}

	if run.BaseSHA != "" {
		fmt.Fprintf(b, "| anchor | `%s` |\n", shortSHA(run.BaseSHA))
	} else {
		b.WriteString("| anchor | **not recorded** — the run has no base commit to diff from |\n")
	}

	// Per-subagent spend, which is the half of the ledger nothing else in the ecosystem can
	// produce: it needs the write-set claims to know who owned what.
	var measured []string
	for _, n := range nodes {
		if n.Kind != "subagent" {
			continue
		}
		if u, ok := usg[n.NodeID]; ok && totalTokens(u) > 0 {
			name := n.Domain
			if name == "" {
				name = n.AgentID
			}
			measured = append(measured, fmt.Sprintf("%s %s", name, render.Tokens(totalTokens(u))))
		}
	}
	if len(measured) > 0 {
		fmt.Fprintf(b, "| by subagent | %s |\n", strings.Join(measured, " · "))
	}

	var owned int
	for _, files := range ws {
		owned += len(files)
	}
	if owned > 0 {
		fmt.Fprintf(b, "| write-sets | %d file(s) claimed across %d agent(s), disjoint by "+
			"construction |\n", owned, len(ws))
	}
	b.WriteString("\n")
}

// unitTitle pulls the unit's heading out of the plan document, so the PR title is the one the
// backlog already gave it rather than one batten made up.
func unitTitle(sp *spec.Spec, unit string) string {
	if sp.Unit.Plan == "" {
		return ""
	}
	b, err := os.ReadFile(filepath.Join(sp.Root, sp.Unit.Plan))
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(b), "\n") {
		if !strings.Contains(line, unit) {
			continue
		}
		s := strings.TrimSpace(strings.TrimLeft(line, "# "))
		if !strings.HasPrefix(s, unit) {
			continue
		}
		s = strings.TrimSpace(strings.TrimPrefix(s, unit))
		s = strings.TrimSpace(strings.TrimLeft(s, "—-–:"))
		if s != "" {
			return s
		}
	}
	return ""
}
