package vault

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// Obsidian Bases: a .base is a YAML query that Obsidian renders as a live table over the
// frontmatter of the notes in the vault.
//
// LOAD-BEARING CAVEAT (Obsidian forum #104089): the RENDERED ROWS of a .base are not readable
// by any script — a programmatic consumer sees the query, never its results. So a .base is a
// HUMAN view and nothing else. Nothing in batten may ever read one back, and no feature may be
// designed on the assumption that it could. SQLite stays canonical; these files are write-only
// projections of it, exactly like the .canvas.
//
// Schema (top-level keys): filters, formulas, properties, summaries, views.
//   - filters is recursive: and | or | not, each node an object with exactly ONE key, whose
//     value is a list of expression strings or further such objects.
//   - property namespaces: bare frontmatter names (status), file.* (file.name, file.mtime),
//     formula.*.
//
// Dates are emitted as ISO-8601 UTC, which sorts identically as text and as a date — so
// `sort: started DESC` is correct even if a vault has not typed the property yet.

type base struct {
	Filters    map[string]any      `yaml:"filters,omitempty"`
	Properties map[string]baseProp `yaml:"properties,omitempty"`
	Views      []baseView          `yaml:"views"`
}

type baseProp struct {
	DisplayName string `yaml:"displayName"`
}

type baseView struct {
	Type    string     `yaml:"type"` // table|cards|list
	Name    string     `yaml:"name"`
	Limit   int        `yaml:"limit,omitempty"`
	Order   []string   `yaml:"order,omitempty"`
	GroupBy string     `yaml:"groupBy,omitempty"`
	Sort    []baseSort `yaml:"sort,omitempty"`
}

type baseSort struct {
	Property  string `yaml:"property"`
	Direction string `yaml:"direction"` // ASC|DESC
}

const baseHeader = `# Generated by batten — regenerated on every run; hand edits are overwritten.
# A .base is a HUMAN dashboard: its rendered rows are NOT readable by scripts
# (Obsidian forum #104089). SQLite stays canonical — nothing reads this file back.
`

// eq builds an equality expression against a frontmatter property. strconv.Quote gives the
// string literal the Bases expression language expects, and keeps a project name containing a
// quote from silently breaking every dashboard.
func eq(prop, val string) string {
	return fmt.Sprintf("%s == %s", prop, strconv.Quote(val))
}

// WriteBases writes the human-facing dashboards. Idempotent; safe to call on every run.
func (w *Writer) WriteBases() error {
	if w.Root == "" {
		return ErrNoVault
	}
	for _, f := range w.bases() {
		out, err := yaml.Marshal(f.b)
		if err != nil {
			return err
		}
		body := append([]byte(baseHeader), out...)
		if err := writeIfChanged(filepath.Join(w.projectDir(), f.name+".base"), body); err != nil {
			return err
		}
	}
	return w.writeIndex()
}

// writeIndex gives the folder a front door.
//
// Without it, opening this directory in Obsidian shows three .base files and a runs/ folder with
// nothing to say what any of them are — and two of the columns are easy to misread in ways that
// matter. "Imputed $" is not a bill, and a note is a projection rather than a source of truth.
// A reader who does not know that will act on the wrong thing, so the answer lives where they
// are looking rather than in a README they will not open.
func (w *Writer) writeIndex() error {
	var b strings.Builder
	fmt.Fprintf(&b, "---\nproject: %s\ntype: batten-index\n---\n\n", w.Project)
	fmt.Fprintf(&b, "# %s — run log\n\n", w.Project)
	b.WriteString("Every work item batten governed in this project, as it actually happened: the phases, " +
		"the fan-out, the retries, and the verdict that let the commit through.\n\n")

	b.WriteString("## Dashboards\n\n")
	b.WriteString("- [[open-runs.base|Open runs]] — what is in flight right now\n")
	b.WriteString("- [[blocked-verdicts.base|Blocked verdicts]] — the runs that need a human. " +
		"`blocked` and `none` sit together because they are the same operational fact: the close gate will deny the commit\n")
	b.WriteString("- [[imputed-cost-by-unit.base|Imputed cost by unit]] — most expensive first\n\n")

	b.WriteString("Individual runs live in `runs/`, one note and one canvas per unit. Open a canvas to " +
		"see the path the work actually took rather than the one the plan hoped for.\n\n")

	b.WriteString("## Reading these numbers\n\n")
	b.WriteString("**Tokens** are exact, and they count the parent *and* every subagent — a fan-out counted " +
		"from the parent transcript alone loses most of its own cost.\n\n")
	b.WriteString("**Imputed $** is what those tokens would have cost on the API. It is **not a bill**. " +
		"On a subscription the marginal cost of a token is zero; this column measures the value being " +
		"pulled out of the subscription, not money that left an account.\n\n")
	b.WriteString("A ceiling batten could not measure is reported as unmeasurable rather than as zero. " +
		"If a number is missing here, it is missing because it was never observed.\n\n")

	b.WriteString("---\n\n")
	b.WriteString("_Written by batten. SQLite is canonical; everything in this folder is a projection of it " +
		"and is regenerated. Hand edits are overwritten._\n")

	return writeIfChanged(filepath.Join(w.projectDir(), safeName(w.Project)+".md"), []byte(b.String()))
}

type namedBase struct {
	name string
	b    base
}

// props are the display names shared by every dashboard. They exist to stop a reader from
// mistaking imputed dollars for a bill: on a subscription no token has a marginal dollar cost,
// and this column is what the run WOULD have cost on the API.
func props() map[string]baseProp {
	return map[string]baseProp{
		"status":         {DisplayName: "Status"},
		"phase":          {DisplayName: "Phase"},
		"verdict":        {DisplayName: "Reviewer verdict"},
		"batten_verdict": {DisplayName: "batten check"},
		"evidence_count": {DisplayName: "Evidence"},
		"tokens":         {DisplayName: "Tokens (exact)"},
		"imputed_usd":    {DisplayName: "Imputed $ (never billed)"},
		"started":        {DisplayName: "Started"},
	}
}

func (w *Writer) bases() []namedBase {
	mine := eq("project", w.Project) // one vault can hold many projects; never show someone else's runs

	return []namedBase{
		{
			name: "open-runs",
			b: base{
				Filters:    map[string]any{"and": []any{mine, `status == "running"`}},
				Properties: props(),
				Views: []baseView{{
					Type:  "table",
					Name:  "Open runs",
					Order: []string{"file.name", "phase", "verdict", "evidence_count", "tokens", "imputed_usd", "started"},
					Sort:  []baseSort{{Property: "started", Direction: "DESC"}},
				}},
			},
		},
		{
			// The runs that need a human. "blocked" and "none" are the same operational fact —
			// the close gate will deny the commit — so they belong in one list. `verdict: none`
			// is why the run note always emits the property instead of omitting it.
			//
			// `batten_verdict` is in the same or-clause because the gate needs BOTH halves: a run
			// whose reviewer approved it but whose checks were never run is just as stuck, and
			// while these were one property it was invisible here.
			name: "blocked-verdicts",
			b: base{
				Filters: map[string]any{"and": []any{
					mine,
					map[string]any{"or": []any{
						`verdict == "blocked"`,
						`verdict == "none"`,
						`batten_verdict == "blocked"`,
					}},
				}},
				Properties: props(),
				Views: []baseView{{
					Type:    "table",
					Name:    "Blocked verdicts",
					Order:   []string{"file.name", "status", "phase", "verdict", "batten_verdict", "evidence_count", "started"},
					GroupBy: "verdict",
					Sort:    []baseSort{{Property: "started", Direction: "DESC"}},
				}},
			},
		},
		{
			// `imputed_usd > 0` is not a cosmetic filter: a run whose transcript was never
			// ingested has NO imputed_usd property, and it must stay out of a cost table rather
			// than appear as $0.00 — an unmeasured run is not a free run.
			name: "imputed-cost-by-unit",
			b: base{
				Filters:    map[string]any{"and": []any{mine, "imputed_usd > 0"}},
				Properties: props(),
				Views: []baseView{{
					Type:  "table",
					Name:  "Imputed cost by unit",
					Order: []string{"file.name", "status", "verdict", "tokens", "imputed_usd", "started"},
					Sort:  []baseSort{{Property: "imputed_usd", Direction: "DESC"}},
				}},
			},
		},
	}
}
