package install

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The Windows binary carries no VERSIONINFO resource by default — a Go .exe has no CompanyName,
// no ProductName, no LegalCopyright, where every legitimate Windows program has all three. Their
// absence is one of the cheap negative signals a heuristic scanner still has to work with, and
// filling them in was measured at 1024 bytes on a 15 MB binary.
//
// What these guards hold is the WIRING, which is the part that rots silently: the resource is
// generated by a hook, from a config file, into a gitignored .syso. Any one of those three coming
// loose produces a release that builds green and ships a blank Details tab, and nobody would
// notice until someone opened Properties on a downloaded file.
//
// What they deliberately do NOT claim: that any of this stops Windows Defender flagging the
// binary. Nothing does — see the Windows note in docs/INSTALL.md. A test that promised that would
// be a test that lies.

// versionInfo mirrors only the fields asserted on. goversioninfo accepts many more.
type versionInfo struct {
	StringFileInfo struct {
		CompanyName      string
		FileDescription  string
		InternalName     string
		LegalCopyright   string
		OriginalFilename string
		ProductName      string
	}
}

func TestTheWindowsVersionResourceIsDeclaredAndComplete(t *testing.T) {
	root := repoRoot(t)

	raw, err := os.ReadFile(filepath.Join(root, "cmd", "batten", "versioninfo.json"))
	if err != nil {
		t.Fatalf("cmd/batten/versioninfo.json is the source of every field Windows shows in the "+
			"Details tab; without it the released .exe has a blank one: %v", err)
	}

	var vi versionInfo
	if err := json.Unmarshal(raw, &vi); err != nil {
		t.Fatalf("versioninfo.json does not parse, so gen-winres would fail at release time: %v", err)
	}

	// Each of these is a field Explorer renders. An empty one is the default a Go binary already
	// has, so an empty one means this whole mechanism bought nothing.
	for name, got := range map[string]string{
		"CompanyName":      vi.StringFileInfo.CompanyName,
		"FileDescription":  vi.StringFileInfo.FileDescription,
		"InternalName":     vi.StringFileInfo.InternalName,
		"LegalCopyright":   vi.StringFileInfo.LegalCopyright,
		"OriginalFilename": vi.StringFileInfo.OriginalFilename,
		"ProductName":      vi.StringFileInfo.ProductName,
	} {
		if strings.TrimSpace(got) == "" {
			t.Errorf("StringFileInfo.%s is empty — that is exactly the state a Go .exe ships in "+
				"without this file, so leaving it blank makes the resource pointless", name)
		}
	}

	// OriginalFilename is the one field that can drift into a lie: it names the file, and the
	// file is named by .goreleaser.yaml's `binary:`. Windows shows both, side by side.
	if got := vi.StringFileInfo.OriginalFilename; got != "batten.exe" {
		t.Errorf("OriginalFilename is %q, but .goreleaser.yaml builds `binary: batten`, so the "+
			"released file is batten.exe — Explorer would show a name that is not the file's", got)
	}
}

func TestTheReleaseGeneratesTheVersionResourceAndTrimsPaths(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, ".goreleaser.yaml"))
	if err != nil {
		t.Fatalf("read .goreleaser.yaml: %v", err)
	}
	cfg := string(raw)

	// Without the hook, versioninfo.json is a file nothing reads and the release ships blank.
	if !strings.Contains(cfg, "scripts/gen-winres.sh") {
		t.Error(".goreleaser.yaml never runs scripts/gen-winres.sh, so no .syso exists at build " +
			"time and the released .exe carries no version resource at all")
	}

	// -trimpath is a privacy fix here, measured, not assumed — see the sibling test below.
	if !strings.Contains(cfg, "-trimpath") {
		t.Error(".goreleaser.yaml does not pass -trimpath, so every published binary embeds the " +
			"build machine's absolute source paths — the author's username included")
	}
}

// The gap this closes: the CI personal-path check and TestNoPrivateProjectTokensAreTracked both
// read FILES. Neither can see inside a compiled binary, and the binary is the one artifact a
// stranger downloads. A `-s -w` build without -trimpath embeds
// C:/Users/<user>/.../cmd/batten/main.go for every file in the main package — stripping symbols
// does not remove those, which is precisely the trap: the release looked stripped and clean.
func TestTheReleasedBinaryLeaksNoPersonalPaths(t *testing.T) {
	if testing.Short() {
		t.Skip("compiles a windows binary")
	}
	root := repoRoot(t)

	out := filepath.Join(t.TempDir(), "batten.exe")
	// The release flags, verbatim. Testing anything else would prove something about a build
	// nobody ships.
	cmd := exec.Command("go", "build", "-trimpath", "-ldflags", "-s -w", "-o", out, "./cmd/batten")
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GOOS=windows", "GOARCH=amd64", "CGO_ENABLED=0")
	if b, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("build: %v\n%s", err, b)
	}

	bin, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read built binary: %v", err)
	}

	// The home prefixes of all three platforms, since the release cross-compiles from whichever
	// one CI happens to run on.
	for _, needle := range []string{`:\Users\`, `:/Users/`, `/home/`, `/Users/`} {
		if i := indexOf(bin, needle); i >= 0 {
			t.Errorf("the built binary contains %q at offset %d (%q) — a published binary must "+
				"not carry the build machine's home directory", needle, i, window(bin, i))
		}
	}
}

func indexOf(hay []byte, needle string) int { return strings.Index(string(hay), needle) }

func window(b []byte, i int) string {
	lo, hi := i-24, i+64
	if lo < 0 {
		lo = 0
	}
	if hi > len(b) {
		hi = len(b)
	}
	return string(b[lo:hi])
}

func TestTheGeneratedResourcesAreNotTracked(t *testing.T) {
	root := repoRoot(t)

	// git ls-files, not os.Stat: the question is whether a clone RECEIVES these, and only the
	// index answers that. A .syso sitting untracked on this machine is invisible to every clone,
	// and os.Stat cannot tell the two apart. (internal/spec's fileIsTracked learned this first.)
	out, err := exec.Command("git", "-C", root, "ls-files", "cmd/batten").Output()
	if err != nil {
		t.Skipf("git unavailable: %v", err)
	}

	for _, f := range strings.Fields(string(out)) {
		if strings.HasSuffix(f, ".syso") {
			t.Errorf("%s is tracked, but it is generated from versioninfo.json plus the tag. A "+
				"committed .syso is a stale version resource waiting to ship: it would pin "+
				"whatever number was current the day it was committed", f)
		}
	}
}
